DELETE http://localhost:3003/api/blogs/666dfa06f1bda94b94fd0cf0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuZ2VsaXZhbm92IiwiaWQiOiI2NjY2NzcyYTIzM2UyY2UxMmZhNDFhNjIiLCJpYXQiOjE3MTg0ODM2MDcsImV4cCI6MTcxODQ4NzIwN30.ws-de3NiCAXXLlp79Z4fY5kBHYtJySBuki9C1jhGZBY